Accept two dirs or ncdu export files, then run ncdu to diff them
lilydjwg/ncdu-diff pull request #1
Opened 2017-09-03 01:33 UTC by goreliu

2017-09-03 03:30 UTC, lilydjwg requested changes

2017-09-03 03:30 UTC, lilydjwg commented on ncdu-diff
> +    os.system("ncdu -o .ncdu-left.tmp %s 2>/dev/null" % fa)
这条命令在文件名包含空格等特殊字符时会出错。推荐使用 subprocess，并且不调用 shell。临时文件用 tempfile 比较好（避开权限、清理问题）。

另外根据是否为目录来判断不好，要是用户手误了呢？（依赖补全的时候经常会传错文件名）

2017-09-03 03:30 UTC, lilydjwg commented on ncdu-diff
> +    fa=".ncdu-left.tmp"
等号两边应该有空格。

2017-09-18 04:21 UTC, goreliu commented
主要问题是 diff 的结果是错的。想了下感觉自己用不到这个，就不改了，不好意思。

2017-09-18 04:22 UTC, closed without merging